export interface ChecklistItem {
  id: string;
  text: string;
}

export interface ChecklistSection {
  id: string;
  title: string;
  items: ChecklistItem[];
}

export const checklistSections: ChecklistSection[] = [
  {
    id: "instalacoes",
    title: "Instalações",
    items: [
      { id: "1", text: "Área externa livre de focos de insalubridade, objetos em desuso, animais e insetos." },
      { id: "2", text: "Acesso direto e independente, não comum a outros usos (habitação)." },
      { id: "3", text: "Fluxo ordenado, sem cruzamento de etapas e atividades." },
      { id: "4", text: "Separação adequada das diferentes atividades por meios físicos ou técnicos." },
      { id: "5", text: "Piso: revestimento liso, impermeável e lavável." },
      { id: "5.1", text: "Piso: em adequado estado de conservação (livre de defeitos, rachaduras, trincas, buracos)." },
      { id: "5.2", text: "Piso: sistema de drenagem dimensionado e sem acúmulo de água." },
      { id: "5.3", text: "Piso: ralos sifonados e grelhas com dispositivo de fechamento." },
      { id: "6", text: "Parede: revestimento liso, impermeável e lavável." },
      { id: "6.1", text: "Parede: em adequado estado de conservação (livre de falhas, rachaduras, umidade, bolor)." },
      { id: "6.2", text: "Parede: pintura em cores claras, lavável e sem desprendimento de tinta." },
      { id: "6.3", text: "Parede: higienizada e em adequado estado de conservação." },
      { id: "7", text: "Teto: revestimento liso, impermeável, lavável e em cor clara." },
      { id: "7.1", text: "Teto: em adequado estado de conservação (livre de trincas, rachaduras, umidade, bolor)." },
      { id: "7.2", text: "Teto: higienizado." },
      { id: "7.3", text: "Teto: ausência de objetos pendurados em desacordo com as Boas Práticas." },
      { id: "8", text: "Portas com superfície lisa, de fácil higienização, ajustadas aos batentes, sem falhas de revestimento." },
      { id: "8.1", text: "Portas externas com fechamento automático (mola, sistema eletrônico ou outro)." },
      { id: "8.2", text: "Portas externas com barreiras adequadas para impedir entrada de vetores e pragas urbanas." },
      { id: "9", text: "Janelas com superfície lisa, de fácil higienização, ajustadas aos batentes." },
      { id: "9.1", text: "Janelas providas de telas milimétricas removíveis para limpeza." },
      { id: "9.2", text: "Janelas em adequado estado de conservação." },
      { id: "10", text: "Iluminação adequada às atividades realizadas." },
      { id: "10.1", text: "Luminárias com proteção contra explosão e quedas acidentais." },
      { id: "10.2", text: "Instalações elétricas embutidas ou externas revestidas por tubulações isolantes e firmemente fixadas." },
      { id: "10.3", text: "Instalações elétricas em adequado estado de conservação." },
      { id: "11", text: "Ventilação garantindo conforto térmico e ambiente livre de fungos, gases, fumaça e condensação." },
      { id: "11.1", text: "Ar insuflado sem incidência direta sobre os alimentos." },
      { id: "11.2", text: "Equipamentos e filtros higienizados periodicamente." },
      { id: "11.3", text: "Sistema de exaustão dimensionado adequadamente." },
      { id: "11.4", text: "Registro periódico de manutenção dos equipamentos de climatização." },
      { id: "12", text: "Eliminação adequada de águas servidas, sem acúmulo e sem refluxo." },
      { id: "13", text: "Água de abastecimento proveniente de fonte adequada e dentro dos padrões de potabilidade." },
      { id: "13.1", text: "Volume e pressão suficientes para atender todas as atividades." },
      { id: "13.2", text: "Caixa d'água em adequado estado de conservação, livre de rachaduras e vazamentos." },
      { id: "13.3", text: "Caixa d'água higienizada periodicamente (mínimo a cada 6 meses), com registro." },
      { id: "14", text: "Instalações sanitárias sem comunicação direta com a área de produção e refeições." },
      { id: "14.1", text: "Instalações sanitárias em adequado estado de conservação." },
      { id: "14.2", text: "Instalações sanitárias higienizadas com frequência adequada." },
      { id: "14.3", text: "Portas com fechamento automático." },
      { id: "14.4", text: "Lavatórios com sabonete líquido inodoro, antisséptico e papel toalha não reciclado." },
      { id: "14.5", text: "Coletores de papel acionados sem contato manual." },
      { id: "14.6", text: "Vestiários separados por sexo, com armários individuais." },
      { id: "15", text: "Lavatórios exclusivos para higienização das mãos na área de manipulação, em posição estratégica." },
      { id: "15.1", text: "Lavatórios com sabonete líquido inodoro, antisséptico e papel toalha não reciclado." },
      { id: "15.2", text: "Lavatórios com coletores de papel acionados sem contato manual." },
      { id: "15.3", text: "Lavatórios com cartazes orientando a correta higienização das mãos." },
    ],
  },
  {
    id: "equipamentos",
    title: "Equipamentos, móveis e utensílios",
    items: [
      { id: "16", text: "Equipamentos da linha de produção com desenho e número que permitem operação, limpeza e manutenção adequadas." },
      { id: "17", text: "Superfícies em contato com alimentos lisas, íntegras, impermeáveis, resistentes à corrosão, sem rugosidades." },
      { id: "18", text: "Em adequado estado de conservação e funcionamento." },
      { id: "19", text: "Equipamentos de conservação dos alimentos (refrigeradores, freezers) com medidor de temperatura calibrado." },
      { id: "20", text: "Existência de planilha de registro de manutenção preventiva e calibração de equipamentos." },
    ],
  },
  {
    id: "higienizacao",
    title: "Higienização de instalações, equipamentos, móveis e utensílios",
    items: [
      { id: "21", text: "Existência de registro periódico da higienização de instalações e equipamentos." },
      { id: "21.1", text: "Produtos de higienização regularizados pelo Ministério da Saúde." },
      { id: "21.2", text: "Disponibilidade de produtos saneantes em quantidade suficiente." },
      { id: "21.3", text: "Diluição, tempo de contato e modo de uso conforme instruções do fabricante." },
      { id: "21.4", text: "Produtos armazenados em local reservado, identificados e separados dos alimentos." },
      { id: "21.5", text: "Utensílios e equipamentos usados na higienização distintos dos usados na manipulação dos alimentos." },
    ],
  },
  {
    id: "pragas",
    title: "Controle integrado de vetores e pragas urbanas",
    items: [
      { id: "22", text: "Ausência de vetores e pragas urbanas ou qualquer evidência de sua presença." },
      { id: "23", text: "Adoção de medidas preventivas e corretivas para impedir a atração, abrigo e proliferação de vetores." },
      { id: "24", text: "Quando aplicado controle químico, empresa especializada e registrada nos órgãos competentes." },
    ],
  },
  {
    id: "agua",
    title: "Abastecimento de água",
    items: [
      { id: "25", text: "Utilização de água potável para manipulação de alimentos." },
      { id: "26", text: "Quando utilizada solução alternativa, comprovada potabilidade semestral." },
      { id: "27", text: "Sistema de captação protegido (poços e cisternas)." },
      { id: "28", text: "Reservatório acessível com instalação hidráulica em adequada conservação." },
      { id: "29", text: "Gelo produzido com água potável, mantido em condições higiênico-sanitárias." },
      { id: "30", text: "Vapor gerado a partir de água potável, livre de substâncias contaminantes." },
    ],
  },
  {
    id: "residuos",
    title: "Manejo dos resíduos",
    items: [
      { id: "31", text: "Recipientes de coleta interna identificados e higienizados constantemente." },
      { id: "32", text: "Uso de sacos de lixo apropriados; quando reutilizáveis, materiais que facilitem higienização." },
      { id: "33", text: "Coletores tampados, com acionamento não manual." },
      { id: "34", text: "Resíduos armazenados em local fechado e isolado da área de manipulação." },
    ],
  },
  {
    id: "manipuladores",
    title: "Manipuladores",
    items: [
      { id: "35", text: "Controle de saúde dos manipuladores realizado e registrado." },
      { id: "36", text: "Manipuladores afastados quando apresentam lesões e/ou sintomas que comprometam a qualidade." },
      { id: "37", text: "Asseio pessoal: boa apresentação, asseio corporal, mãos limpas, unhas curtas sem esmalte." },
      { id: "38", text: "Lavagem cuidadosa das mãos antes da manipulação e após qualquer interrupção." },
      { id: "39", text: "Cartazes de orientação sobre a correta lavagem das mãos em locais estratégicos." },
      { id: "40", text: "Manipuladores não fumam, não falam desnecessariamente, não cantam, não assobiam, não espirram, não tossem sobre os alimentos." },
      { id: "41", text: "Uniformes de trabalho de cor clara, adequados, limpos e em bom estado de conservação." },
      { id: "42", text: "Programa de capacitação adequado e contínuo, com registros." },
      { id: "43", text: "Visitantes com uniforme apropriado." },
    ],
  },
  {
    id: "materias-primas",
    title: "Matérias-primas, ingredientes e embalagens",
    items: [
      { id: "44", text: "Critérios estabelecidos para seleção e qualificação de fornecedores." },
      { id: "45", text: "Recepção em área protegida e limpa." },
      { id: "46", text: "Inspeção visual no recebimento, com avaliação do veículo e embalagens." },
      { id: "47", text: "Matérias-primas e ingredientes aguardando liberação identificados." },
      { id: "48", text: "Matérias-primas, ingredientes e embalagens armazenados sobre paletes, estrados e/ou prateleiras." },
      { id: "49", text: "Embalagens primárias íntegras, sem contato direto com piso, paredes e teto." },
      { id: "50", text: "Validade respeitada para todos os insumos." },
    ],
  },
  {
    id: "preparacao",
    title: "Preparação do alimento",
    items: [
      { id: "51", text: "Adoção de medidas para evitar contaminação cruzada." },
      { id: "52", text: "Manipuladores que atuam em diferentes atividades adotam medidas para evitar contaminação cruzada." },
      { id: "53", text: "Matérias-primas e ingredientes higienizados antes do uso." },
      { id: "54", text: "Procedimentos específicos para higienização de hortifrutícolas, com produtos regularizados." },
      { id: "55", text: "Descongelamento conduzido sob refrigeração (≤ 5°C) ou em forno de micro-ondas." },
      { id: "56", text: "Alimentos descongelados não recongelados antes ou após preparo." },
      { id: "57", text: "Alimentos preparados mantidos em condições de tempo e temperatura que evitem multiplicação microbiana." },
      { id: "58", text: "Tratamento térmico atinge no mínimo 70°C no centro geométrico do alimento." },
      { id: "59", text: "Óleos e gorduras utilizados em frituras não aquecidos acima de 180°C, substituídos quando apresentarem alterações." },
      { id: "60", text: "Após cocção, alimentos expostos a quente mantidos acima de 60°C por no máximo 6 horas." },
      { id: "61", text: "Após cocção, alimentos resfriados de 60°C a 10°C em no máximo 2 horas." },
      { id: "62", text: "Resfriamento conduzido em equipamento adequado." },
      { id: "63", text: "Alimentos resfriados conservados sob refrigeração (≤ 5°C) ou congelados." },
      { id: "64", text: "Para conservação a quente, equipamentos mantendo temperatura ≥ 60°C." },
      { id: "65", text: "Para conservação sob refrigeração ou congelamento, temperatura conforme recomendação do fabricante." },
      { id: "66", text: "Alimentos crus higienizados de forma a reduzir a contaminação superficial." },
    ],
  },
  {
    id: "armazenamento",
    title: "Armazenamento e transporte do alimento preparado",
    items: [
      { id: "67", text: "Alimentos preparados armazenados em recipientes cobertos, identificados, com data de preparo e validade." },
      { id: "68", text: "Armazenamento sob temperatura adequada conforme o tipo de alimento." },
      { id: "69", text: "Meios de transporte mantidos em condições higiênico-sanitárias adequadas." },
    ],
  },
  {
    id: "exposicao",
    title: "Exposição ao consumo do alimento preparado",
    items: [
      { id: "70", text: "Área de exposição mantida organizada e em adequadas condições higiênico-sanitárias." },
      { id: "71", text: "Equipamentos e utensílios disponíveis em quantidade suficiente, mantendo temperaturas adequadas." },
      { id: "72", text: "Manipuladores realizam antissepsia das mãos." },
      { id: "73", text: "Existência de barreiras de proteção (anteparos) na exposição." },
      { id: "74", text: "Utensílios para consumo (pratos, talheres, copos) higienizados e armazenados em local protegido. Área de recebimento de dinheiro separada da manipulação." },
    ],
  },
  {
    id: "documentacao",
    title: "Documentação e registro",
    items: [
      { id: "75", text: "Manual de Boas Práticas disponível para os funcionários e acessível à autoridade sanitária." },
      { id: "76", text: "Procedimentos Operacionais Padronizados (POPs) elaborados, aprovados, datados e assinados." },
      { id: "77", text: "POP de higienização de instalações, equipamentos, móveis e utensílios implementado." },
      { id: "78", text: "POP de controle integrado de vetores e pragas urbanas implementado." },
      { id: "79", text: "POP de higienização do reservatório de água implementado." },
      { id: "80", text: "POP de higiene e saúde dos manipuladores implementado." },
      { id: "81", text: "Registros mantidos por período mínimo de 30 dias." },
      { id: "82", text: "Programa de capacitação de manipuladores documentado." },
    ],
  },
];

export const totalChecklistItems = checklistSections.reduce((acc, s) => acc + s.items.length, 0);
