/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadoRouteImport } from './routes/resultado'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MeuResultadoRouteImport } from './routes/meu-resultado'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcessoNegadoRouteImport } from './routes/acesso-negado'
import { Route as IndexRouteImport } from './routes/index'

const ResultadoRoute = ResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuResultadoRoute = MeuResultadoRouteImport.update({
  id: '/meu-resultado',
  path: '/meu-resultado',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcessoNegadoRoute = AcessoNegadoRouteImport.update({
  id: '/acesso-negado',
  path: '/acesso-negado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/admin': typeof AdminRoute
  '/checklist': typeof ChecklistRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/meu-resultado': typeof MeuResultadoRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resultado': typeof ResultadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/admin': typeof AdminRoute
  '/checklist': typeof ChecklistRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/meu-resultado': typeof MeuResultadoRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resultado': typeof ResultadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/acesso-negado': typeof AcessoNegadoRoute
  '/admin': typeof AdminRoute
  '/checklist': typeof ChecklistRoute
  '/historico': typeof HistoricoRoute
  '/login': typeof LoginRoute
  '/meu-resultado': typeof MeuResultadoRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resultado': typeof ResultadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/acesso-negado'
    | '/admin'
    | '/checklist'
    | '/historico'
    | '/login'
    | '/meu-resultado'
    | '/perfil'
    | '/reset-password'
    | '/resultado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/acesso-negado'
    | '/admin'
    | '/checklist'
    | '/historico'
    | '/login'
    | '/meu-resultado'
    | '/perfil'
    | '/reset-password'
    | '/resultado'
  id:
    | '__root__'
    | '/'
    | '/acesso-negado'
    | '/admin'
    | '/checklist'
    | '/historico'
    | '/login'
    | '/meu-resultado'
    | '/perfil'
    | '/reset-password'
    | '/resultado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcessoNegadoRoute: typeof AcessoNegadoRoute
  AdminRoute: typeof AdminRoute
  ChecklistRoute: typeof ChecklistRoute
  HistoricoRoute: typeof HistoricoRoute
  LoginRoute: typeof LoginRoute
  MeuResultadoRoute: typeof MeuResultadoRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultadoRoute: typeof ResultadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultado': {
      id: '/resultado'
      path: '/resultado'
      fullPath: '/resultado'
      preLoaderRoute: typeof ResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-resultado': {
      id: '/meu-resultado'
      path: '/meu-resultado'
      fullPath: '/meu-resultado'
      preLoaderRoute: typeof MeuResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acesso-negado': {
      id: '/acesso-negado'
      path: '/acesso-negado'
      fullPath: '/acesso-negado'
      preLoaderRoute: typeof AcessoNegadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcessoNegadoRoute: AcessoNegadoRoute,
  AdminRoute: AdminRoute,
  ChecklistRoute: ChecklistRoute,
  HistoricoRoute: HistoricoRoute,
  LoginRoute: LoginRoute,
  MeuResultadoRoute: MeuResultadoRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultadoRoute: ResultadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
